#!/usr/bin/env bash

args=($(printf "%s\n" $@))
args[0]=git
cmd=${args[1]}
[[ "$@" != "${@% }" ]] && trail=1

# ==============================================================================
# LIST ALL COMMANDS
# ==============================================================================
function all_commands() {
	printf "%s\n" $(git help --all | grep '^ \+\w')
	git config --list | sed -n 's/^alias\.\([^=]\+\)=\(.*\)/\1 (alias for \2)/p'
}

# Check if command empty
if [[ -z $cmd ]]; then
	result=($(all_commands | my-fzf-40))
	ret=$?

# Check for command tab complete
elif [[ -z ${args[2]} && -z $trail ]]; then
	result=($(all_commands | my-fzf-40 $cmd))
	ret=$?
fi

# Return results (if available)
if [[ -n $ret ]]; then
	[[ $ret -ne 0 ]] && exit $ret
	echo "git ${result[0]} "
	exit 0
fi


# ==============================================================================
# SPECIFIC COMMANDS
# ==============================================================================
git_top=$(git rev-parse --show-toplevel)
git_relative=$(python -c "import os.path; print os.path.relpath('$git_top', '$PWD')")

if [[ $cmd =~ add|diff ]]; then
	result=($({
		my-fzf-helper-git-files
	} | my-fzf-git-diff '!ignore'))
	ret=$?
	args+=(${result[1]})

elif [[ $cmd == 'diff' ]]; then
	result=$(git ls-files --modified | my-fzf-40)
	ret=$?
	args+=($result)

else
	result=$({
		my-fzf-helper-files-shallow-first
	} | my-fzf-40)
	ret=$?
	args+=(${result[0]})
fi

# Return result
[[ $ret -ne 0 ]] && exit $ret
echo "${args[@]} "

